# Generated by Django 2.2.6 on 2019-10-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20191022_2108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=300)),
                ('detail', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
