# Generated by Django 2.2.6 on 2019-10-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20191022_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=1000)),
                ('phone', models.CharField(max_length=1000)),
                ('mess', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('detail', models.CharField(max_length=1000)),
                ('photo', models.CharField(max_length=1000)),
                ('url', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
