# Generated by Django 2.2.6 on 2019-10-26 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0006_auto_20191026_2256'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=1000)),
                ('phone', models.CharField(max_length=1000)),
                ('mess', models.CharField(max_length=1000)),
                ('time', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('detail', models.CharField(max_length=1000)),
                ('photo', models.CharField(max_length=1000)),
                ('url', models.CharField(max_length=1000)),
            ],
        ),
    ]
